# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: 桃李不言
email: 3944134@qq.com
description: > # this means to ignore newlines until "baseurl:"
    客观平和，坚持自我
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://ericluo.github.io" # the base hostname & protocol for your site
twitter_username: jekyllrb
xueqiu_username:  sailor
github_username:  ericluo

cloud_url: http://7xonmk.com1.z0.glb.clouddn.com
# Build settings
markdown: kramdown

paginate: 5

kramdown:
    auto_ids: true
    footnote_nr: 1
    entity_output: as_char
    toc_levels: 1..4

tag_page_layout: tag_page
tag_page_dir: tag    

# Plugins
# gems:
#    - jekyll-mentions
#    - jekyll-sitemap


